AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
Layout/LineLength:
  Enabled: 100
Metrics/BlockLength:
  Exclude:
    # Test blocks are long.
    - test/**/*_test.rb
    - reynard.gemspec
Metrics/ClassLength:
  Enabled: 150
  Exclude:
    # Test classes are long.
    - test/**/*_test.rb
Metrics/MethodLength:
  Max: 14
  Exclude:
    # Test methods are long.
    - test/**/*_test.rb
Style/AsciiComments:
  Enabled: false
# The Specification class defines its own dig method and that must work with a single argument.
Style/SingleArgumentDig:
  Enabled: false
