AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
Layout/LineLength:
  Enabled: 100
Metrics/ClassLength:
  Exclude:
    # Test classes are long.
    - test/**/*_test.rb
Metrics/MethodLength:
  Max: 14
  Exclude:
    # Test methods are long.
    - test/**/*_test.rb
Style/AsciiComments:
  Enabled: false
# We use OpenStruct exactly what it was created for; objects with schema on read.
Style/OpenStructUse:
  Enabled: false
# The Specification class defines its own dig method and that must work with a single argument.
Style/SingleArgumentDig:
  Enabled: false
