name: Run tests
on: [push]
jobs:
  build:
    strategy:
      matrix:
        version: ["ruby:3.4", "ruby:3.3", "ruby:3.2"]
    runs-on: ubuntu-latest
    container: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Bundler cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.version }}-bundler-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Bundler and Rubocop
        run: |
          gem install --no-document bundler rubocop rubocop-performance
          bundle config set path 'vendor/bundle'
          bundle install --jobs 3 --retry 3
      - name: Run tests
        run: |
          bundle exec rake
          rubocop
